### ISSUE TITLE
【単体テスト】複数件のCSVをアップしたときにエラーとなる

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#1]
@ShinjiroMoriya 
表題の件、複数件のCSVでインポート実施時に、最初の1件は登録されたのですが2件目以降がエラーですべて落ちたようです。
対象のCSVは添付の[（賃貸革命）家主基本情報.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13330879/default.csv)となり、データは48件あります。

またエラーステータスや表示件数もすべて0になっているようで、こちらもインポート出来た際には全件と失敗件数を表示したいです。

## heroku画面
![スクリーンショット 2023-11-13 13 59 55](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/b4fcac55-60c9-4bf2-a5ff-28fc7d01130b)

## エラー内容
![スクリーンショット 2023-11-13 14 04 02](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/714529a0-de87-468f-ade5-efa409fb42bc)

## 取引先に取り込めた1件のデータ
![スクリーンショット 2023-11-13 14 03 27](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/7b7eedf8-eeea-4cf8-9146-92fd3ecb6813)

**Comment by ShinjiroMoriya** [comment]
これは構造上のエラーなので件数は合わないです。

調整したものを反映しました。試してみてください。

**Comment by ao-utah** [comment]
ありがとうございます！再インポートしてみます！

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
同じCSVで再インポートしたところ別のエラーが発生したようです。
↓こちら再度ご確認のほどお願いいたします！

'coroutine' object has no attribute 'correctedupload'

![スクリーンショット 2023-11-13 14 46 13](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/9a2e32ac-93af-4178-a610-fa3f02ff4345)

**Comment by ShinjiroMoriya** [comment]
失礼しました。再調整しました。

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
再インポートを実施したところ、「処理中」のままになるようでした！
SFのアップロード実行ログを確認したところ、こちらも「処理中」だったので、裏側で処理が止まったかもしれませんん。
再度ご確認のほどよろしくお願いいたします

![スクリーンショット 2023-11-13 14 55 54](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/1ce09387-3477-4f12-8b00-d7a1888bc8e8)

![スクリーンショット 2023-11-13 14 56 12](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/5b41da95-d518-47f4-a52c-d81efaf6a987)

**Comment by ShinjiroMoriya** [comment]
デプロイ中にアップロードしてしまっているようです。
リロードしてもう一度やってみてください。

**Comment by ao-utah** [comment]
失礼しました！再度試します！

**Comment by ao-utah** [comment]
ありがとうございます！複数件のインポート実施できました！
本件はクローズいたします。
今後細かい変換処理や更新処理のテスト実施していきます
