### ISSUE TITLE
【単体テスト】（物件基本情報）「貸主名」「物件所有者」「その他貸主名」「その他所有者名」がセットされない

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#12]
@ShinjiroMoriya 

物件情報をアップロードした際に「貸主名」「物件所有者」「その他貸主名」「その他所有者名」がセットされないようで、こちらの修正のほどお願いできますでしょうか？？

![スクリーンショット 2023-11-27 16 34 04](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/97e92013-9e40-4e80-8005-81863be158a4)

・「貸主名」「物件所有者」「その他貸主名」は参照項目、
・「その他所有者名」はテキスト項目（変換不要）となります。
（※1点すみません設定ミスで「その他所有者名」の型がSF上で参照項目になっておりました、これは誤りなのでさきほどテキスト型に変更しました。heroku connectもつなぎ直したのでおそらく問題ないと思いますが、念のため共有です。）

↓変換仕様は下記となります
![スクリーンショット 2023-11-27 16 36 20](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/aeea7051-157a-4921-8f67-34c228e8e518)
https://docs.google.com/spreadsheets/d/1txbpW5g9MXMCRB82j9vaCW8debBDwZLFARKcvVEYBJs/edit#gid=1113721135&range=AK55:AV58

**Comment by ShinjiroMoriya** [comment]
アップロードしたCSVください

**Comment by ao-utah** [comment]
こちら確認Okでした！ご対応ありがとうございます
