### ISSUE TITLE
【単体テスト】（空室一覧情報）csvアップロード後に全く同じ内容のcsvをアップするとエラーになる

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#14]
@ShinjiroMoriya 
#13 と同じ事象みたいです
ご確認のほどお願いいたします

![スクリーンショット 2023-11-27 17 13 26](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/ed332e8e-547a-497e-afcf-da420aaa6483)

```
'RoomC' object has no attribute 'recordtypeid'
```

![スクリーンショット 2023-11-27 17 13 10](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/99c149b2-494e-40a0-a119-e3061a3781ba)

**Comment by ShinjiroMoriya** [comment]
すみません。調整しました。
#13 も同様です。

**Comment by ao-utah** [comment]
ありがとうございます！アップできました
本件クローズします
