### ISSUE TITLE
【単体テスト】（物件基本情報（サービス分類））更新キー項目となる「物件名」列の仕様についての調整

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#23]
@ShinjiroMoriya 
賃貸革命の「物件基本情報（サービス分類）」の物件名について、
すみませんこちら元システム側の実データを確認したところ、
物件名が `（{物件NO}）{物件名}`  となっていることがわかりました。

![スクリーンショット 2023-12-04 19 01 10](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/b7774b2c-337a-4c1f-a7ce-ad873b29b4c9)

こちら更新時のキーとして、「物件名」を使用する形で仕様書に記載しておりましたが、そのままキーのチェックを行うと一致しないので、更新がされなくなってしまうため、下記に仕様変更したいのですが調整可能でしょう？？

①物件基本情報（サービス分類）の「物件名」列の（）の物件Noを取りだす
例）`(5478) ヴェルジェ日野` の場合、`5478` を取得する。
②取り出した「物件No」＋「部屋No」が一致する「部屋情報」に対して更新を実施する

↓仕様書のリンクです
https://docs.google.com/spreadsheets/d/1txbpW5g9MXMCRB82j9vaCW8debBDwZLFARKcvVEYBJs/edit#gid=865020106&range=C45
![スクリーンショット 2023-12-04 19 15 22](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/7402f04e-7546-4175-8763-7b6a51344e3e)

**Comment by ao-utah** [comment]
あ、すみませんこちら日をまたいだので、物件と部屋情報を登録する必要があるので、ちょっと準備します。お待ち下さい🙇‍♂

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
すみませんこちら検証のために、事前に「物件情報」と「部屋情報」を登録する必要があるのですが、「部屋情報」がエラーで登録されなくなってしまっているようで一度ご確認をお願いできますでしょうか？？（以前は正常に登録されてたのですが、なぜかエラーになるようで。「物件情報」は正常に登録済みです！）

```
could not convert string to float: ''
```

[（賃貸革命）空室一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13545765/default.csv)

![スクリーンショット 2023-12-04 21 15 29](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/47089982-18b5-4154-ab9e-3400f785346e)
![スクリーンショット 2023-12-04 21 15 51](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/410500cb-24ac-4f52-8858-102ee435159c)

上記の空室一覧のインポート後に、
下記のCSVをアップロードする流れとなります！
[（賃貸革命）物件基本情報（サービス分類）.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13545792/default.csv)

**Comment by ShinjiroMoriya** [comment]
確認がうまくできなかったので、
データ入れてもらってから、再度調整します。

これに関わるCSVをすべてください。

**Comment by ao-utah** [comment]
>これに関わるCSVをすべてください。

最低限必要なcsvは下記となります。上から順番にアップする形となります！

## 12/5作成テストデータcsv
①[（賃貸革命）家主基本情報.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13553863/default.csv)
②[（賃貸革命）物件基本情報.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13553864/default.csv)
③[（賃貸革命）空室一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13553866/default.csv)
④[（賃貸革命）物件基本情報（サービス分類）.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13553870/default.csv)

**Comment by ao-utah** [comment]
@ShinjiroMoriya 

こちらご対応ありがとうございます！
物件情報の更新は正しく確認することができました！
１点、部屋情報側が更新されていないようで、ご確認をお願いできますでしょうか？？

このCSVの仕様ですが、下記となります
・所有形態が「一棟所有」の場合→物件情報側を更新（OK）
・所有形態が「区分所有」の場合→部屋情報側を更新（NG）

![スクリーンショット 2023-12-05 18 25 49](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/7005ec9c-9e69-4529-899e-25f03ce9b2ea)
※テストデータはテストマンション大田の「一棟所有」にしています

あわせて、すみません上段コメントでお送りした `（賃貸革命）物件基本情報（サービス分類）.csv` に一部誤りがあり修正しました

下記で検証いただければと思います

## 修正版テストデータCSV
[（賃貸革命）物件基本情報（サービス分類）.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13557982/default.csv)

**Comment by ao-utah** [comment]
確認OKです！ご対応ありがとうございます
クローズいたします！
