### ISSUE TITLE
【単体テスト】（KASIKA）ケースの件名の先頭に"KASIKA"の文字が付かない

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#34]
KASIKAのCSVをアップロードした際の、　ケース件名の頭に `KASIKA` の文字列が付与されないようで、こちら調整のほどお願いできますでしょうか？
![スクリーンショット 2023-12-04 20 07 15](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/cf26ca7e-7c1c-4282-8fb1-390d948ecc6a)

※テストデータがKASIKA太郎なのでまぎわらしいですが、`KASIKA KASIKA太郎◯◯` みたいになればOKです

![スクリーンショット 2023-12-04 20 04 47](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/a674bc7a-1873-43a5-96ac-ae1c982c4a9f)

↓仕様書へのリンク
https://docs.google.com/spreadsheets/d/1txbpW5g9MXMCRB82j9vaCW8debBDwZLFARKcvVEYBJs/edit#gid=305984796&range=AK53:AV53

## アップロードしたcsv
[（KASIKA）問合せ顧客データ一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13545170/KASIKA.csv)

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
こちら確認しました！
ケースの件名の先頭に文字付与されることを確認しましたが、 `KASHIKA` となっており、`H` は不要なのでこちらだけカットをお願いできますか？

（誤）KASHIKA
（正）KASIKA

**Comment by ao-utah** [comment]
@ShinjiroMoriya 

こちら再度アップして確認したところ、件名が空欄になるようで、
ご確認をお願いできますでしょうか？
![スクリーンショット 2023-12-07 14 38 38](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/70e7850c-a1b2-4dc0-9081-23236ba113af)

## アップロードしたCSV
[（KASIKA）問合せ顧客データ一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13595689/KASIKA.csv)

**Comment by ShinjiroMoriya** [comment]
失礼しました。調整漏れでした。

**Comment by ao-utah** [comment]
確認OKです！ありがとうございます
クローズいたします
