### ISSUE TITLE
【単体テスト】（おまかせくん）区分が"法人"の際に、取引先責任者が作成されない

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#37]
@ShinjiroMoriya 
おまかせくんcsvをアップロードして法人取引先で作成された場合、そのデータの子にあたる取引先責任者が登録されないようで、こちらご確認ご調整のほどお願いできますでしょうか？？
![スクリーンショット 2023-12-04 20 20 34](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/c4969eea-d10e-4341-81c8-ea807ffc5b45)

## アップロードしたcsv
[（おまかせくん）顧客データ.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13545317/default.csv)

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
本件再確認したところ、引き続き事象が発生するようで、
再度ご確認をお願いできますでしょうか？？
![スクリーンショット 2023-12-11 12 51 11](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/28f25719-2c57-49fc-aa5f-deaefb437a4c)

## 再テスト時のアップロードcsv
[（おまかせくん）顧客データ.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13630749/default.csv)

**Comment by ShinjiroMoriya** [comment]
調整しました。データは削除してます。

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
法人取引先のデータ３つが作成されなくなったようで、再度ご確認をお願いできますか？？
作成想定の取引先名は「おまかせテスト株式会社1,2,3」になります


## 取引先
![スクリーンショット 2023-12-12 19 39 31](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/3c4c03a7-1a05-4f87-ab1a-d413d19b403f)

![スクリーンショット 2023-12-12 19 42 19](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/32922a31-7196-4f96-9fe1-4d50c36679f7)
```
{"op": "UPDATE", "src": "SFDC", "msg": "\u53d6\u5f15\u5148 ID: \u4e0d\u6b63\u306a\u7a2e\u5225\u306e ID \u5024: a15cdad2-efed-4648"}
```

## 取引先責任者
![スクリーンショット 2023-12-12 19 39 46](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/5ab8589c-08df-466a-a359-c93b88cfc351)


![スクリーンショット 2023-12-12 19 44 08](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/b0565c64-4a7d-4dce-aa8b-45514a1e1415)

```
{"op": "UPDATE", "src": "SFDC", "msg": "\u53d6\u5f15\u5148\u8cac\u4efb\u8005 ID: \u4e0d\u6b63\u306a\u7a2e\u5225\u306e ID \u5024: 236177fa-1686-4dc1"}
```


##  再テスト時のアップロードcsv
[（おまかせくん）顧客データ.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13647070/default.csv)

**Comment by ao-utah** [comment]
確認OKです！ご対応ありがとうございます
クローズいたします
