### ISSUE TITLE
【単体テスト】（既成約者DM送付リスト） 一部データしか登録されない

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#38]
@ShinjiroMoriya 
#29 と同じような事象なのですが、CSVの末尾のレコードしか登録されないようで、こちらご確認ご調整のほどお願いできますでしょうか？？
`既成約者太郎9` のみ登録されているようで、1~8がスキップされているようです。

![スクリーンショット 2023-12-04 20 34 10](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/3a7ac49b-fce5-4e89-8644-4df01a1efbef)

## アップロードしたcsv
[既成約者DM送付リスト.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13545416/DM.csv)

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
こちら確認しました！
2点再度ご確認お願いできますでしょうか？？

①連名の親に当たるデータが作成されない
![スクリーンショット 2023-12-11 12 42 11](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/c153918e-5608-4d2c-b251-9d4c70a5e07f)

②連名として作成されたレコードの各項目に親と同じ値をセットする
![スクリーンショット 2023-12-11 12 42 26](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/8c16bffd-cc06-47b7-a365-a107a64c43ae)

**Comment by ShinjiroMoriya** [comment]
なんとか入りました。確認ください。
10秒待機して紐付け後にインサートしました。

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
ありとうございます！確認できました！
概ねOKでしたが　`既成約者太郎7，8，9`がFAILEDになっているようで、
再度ご確認お願いいたします。それ以外はすべてOKです

`既成約者太郎7，8，9` は、連名項目の一部が空欄になっている想定のテストデータとなります。`既成約者太郎7，8，9` の子にあたる取引先も正常に作成されています。

![スクリーンショット 2023-12-12 11 40 08](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/1797e9c3-9c52-485a-a49e-f32b65e72800)


## 同期エラー内容
```
select * FROM salesforce.account WHERE _hc_lastop = 'FAILED' AND lastname LIKE '%既成約者%'
```
![スクリーンショット 2023-12-12 11 48 24](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/a1b067b1-3a88-4850-88df-e8b79d020436)

```
{"op": "INSERT", "src": "SFDC", "msg": "DM\u9001\u4ed8\u30ea\u30b9\u30c8 \u9023\u540d3: \u4e0d\u6b63\u306a\u7a2e\u5225\u306e ID \u5024: Account object ()"}
```

## 再テスト時のアップロードCSV
[既成約者DM送付リスト.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13643105/DM.csv)
![スクリーンショット 2023-12-12 11 41 56](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/601f6580-44b0-4797-87a8-dbe806fffcda)

**Comment by ShinjiroMoriya** [comment]
調整しました。データは消してます。

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
ありがとうございます！
7,8,9作成確認できました！

↓こちらの赤枠部分ですが、何故か `家主太郎42` がセットされるようです。
こちらは空欄の部分は、空欄になるよう再度調整お願いできますでしょうか？
![スクリーンショット 2023-12-12 12 23 37](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/b8527d7b-31fb-4d40-9615-1e983e5f1c2d)

**Comment by ShinjiroMoriya** [comment]
調整しました。一度データは削除しました。

**Comment by ao-utah** [comment]
こちら確認すべてOKです！ご対応ありがとうございます！
クローズいたします
