### ISSUE TITLE
【単体テスト】（オフィステナント連絡先設備一覧）アップ時に対象のレントロール詳細がある場合に「取引先名」参照項目に値がセットされない

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#40]
@ShinjiroMoriya 
`オフィステナント連絡先設備一覧` のアップロード時に、一致するレントロール詳細がある場合、その「取引先名」にセットする想定ですが、更新されないようです。

なお、テストデータではレントロール詳細の  `中央テストビル駐車場(6)` に対して、`オフィステスト株式会社1(2023-12-7)` がセットされる想定で用意しております。

![スクリーンショット 2023-12-07 18 31 54](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/0e029911-fcbe-447c-8b03-9102406ad331)

## アップロードしたCSV
[オフィステナント連絡先設備一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13598253/default.csv)

**Comment by ShinjiroMoriya** [comment]
現状「オフィステスト株式会社1(2023-12-7)」は存在しないようなので入れてから確認ください

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
こちら確認OKです！
こちらに関して1点だけご質問です！

>現状「オフィステスト株式会社1(2023-12-7)」は存在しないようなので入れてから確認ください

↑上記の場合、`オフィステナント連絡先一覧` → `レントロール詳細` の順番でアップロードが必要な感じですよね？？

以前、`店舗テナント緊急連絡先一覧`をテストした際は、
`レントロール詳細` → `店舗テナント緊急連絡先一覧` で順番で店舗テナントを後入れでセットできていたのでどちらかに統一したいのですが可能でしょうか？？

※`オフィステナント連絡先一覧`と`店舗テナント緊急連絡先一覧`はほぼ同じ挙動を想定しています。

**Comment by ao-utah** [comment]
@ShinjiroMoriya 
すみませんこちら上段コメントでどちらかに統一とコメントさせてもらったのですが、レントロール詳細に対して、更新して値をセットする必要があることを思い出しました。

アップロードの順番は、`レントロール詳細` → `オフィステナント連絡先一覧`  でお願いできますでしょうか？？

※現在の `店舗テナント緊急連絡先一覧` と同じ挙動となります

![スクリーンショット 2023-12-11 12 59 45](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/27fbdf0a-fa7d-4e24-bc17-0ba635a09b75)

**Comment by ShinjiroMoriya** [comment]
調整してみたので確認お願いします。
データの削除はして無いです。

**Comment by ao-utah** [comment]
確認できました！すべてOKです
ご対応ありがとうございます
クローズいたします
