### ISSUE TITLE
【単体テスト】（店舗テナント緊急連絡先一覧）csvアップロード時に取引先責任者がFAILEDになっている

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#41]
@ShinjiroMoriya
表題の件、以前は問題なく作成できていたのですが、
あらためてアップした際に事象を確認しました。
ご確認のほどお願いできますでしょうか？？

```
select * FROM salesforce.contact WHERE _hc_lastop = 'FAILED' AND lastname LIKE '%店舗%'
```
![スクリーンショット 2023-12-12 21 03 39](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/faf7423b-31a3-4c3b-adda-d20029096b30)

```
{"op": "UPDATE", "src": "SFDC", "msg": "\u53d6\u5f15\u5148\u8cac\u4efb\u8005 ID: \u4e0d\u6b63\u306a\u7a2e\u5225\u306e ID \u5024: 12d49575-e4d1-40f4"}
```

## アップロードしたCSV
[店舗テナント緊急連絡先一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13647832/default.csv)

**Comment by ShinjiroMoriya** [comment]
調整しました。データ削除しました。レントロールは残してます。
