### ISSUE TITLE
【シナリオ】【（賃貸革命）物件基本情報（サービス分類）】更新されるが値がセットされなくなっている

### ISSUE THREAD

**Issue by ao-utah** [re-solver-dev/keio-name-identification-app#47]
@ShinjiroMoriya 

本件、下記のissueで調整いただいて、確認OKだったのですが、

> 【単体テスト】（物件基本情報（サービス分類））更新キー項目となる「物件名」列の仕様についての調整 #23

シナリオテスト時に再確認したところ値が反映されないようで再度ご確認をお願いできますでしょうか？？
（CSVアップロード時は更新日時が最新化されていたようなので更新自体は行われているようでした！）

## 確認手順
下記のCSVを上から順番に流して、対象の部屋情報オブジェクト、または物件情報オブジェクトのデータを確認する

[（賃貸革命）家主基本情報.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13722365/default.csv)
[（賃貸革命）物件基本情報.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13722367/default.csv)
[（賃貸革命）空室一覧.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13722368/default.csv)
[（賃貸革命）物件基本情報（サービス分類）.csv](https://github.com/re-solver-dev/keio-name-identification-app/files/13722370/default.csv)

![スクリーンショット 2023-12-20 11 59 35](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/534c67f4-f29a-419a-be66-bcf0daceeb1b)
![スクリーンショット 2023-12-20 12 00 42](https://github.com/re-solver-dev/keio-name-identification-app/assets/50035788/27e1e9dc-bf78-44ec-83e3-a98cdeca4d58)

**Comment by ShinjiroMoriya** [comment]
<img width="791" alt="スクリーンショット 2023-12-21 1 22 07" src="https://github.com/re-solver-dev/keio-name-identification-app/assets/7581596/b6bb0bac-974b-4600-b779-0f09332b38f7">
カラム名が区分所有になってしまっているようです。正しくは「所有形態」ですよね。

**Comment by ao-utah** [comment]
すみませんこちらテストデータ作成時に誤っておりました。🙇‍♂
修正後、問題なくインポートできました！お手数おかけしました
クローズいたします
